[book]
title = "Thought machine"
authors = ["Viet Le"]
language = "en"
multilingual = false
src = "src"

[output.html]
default-theme = "navy"
preferred-dark-theme = "navy"
git-repository-url = "https://github.com/lttviet/wiki"